sudo: required

language: java

branches:
  only:
  - master
  - /^branch-.*$/

services:
  - docker

env:
  - TMPDIR=/tmp

jdk:
  - openjdk8

before_install:

  # Import decrypt and import gpg keys
  - >
    openssl aes-256-cbc
    -K $encrypted_f1a45c049930_key  -iv $encrypted_f1a45c049930_iv
    -in .gpg-keys/secret.asc.enc -out .gpg-keys/secret.asc -d
  - gpg --import .gpg-keys/public.asc
  - gpg --import .gpg-keys/secret.asc

before_script:
  - mvn scalastyle:check # check scalastyle
  - mvn scala:doc -B # generate/test documentation

after_success:
  - >
    if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      mvn deploy --settings .maven-settings.xml -DskipTests=true -B
      if [ $TRAVIS_BRANCH = 'master' ]; then
        mvn site --settings .maven-settings.xml -B
      fi
    fi
